# fly.toml app configuration file generated for docs-gpt on 2023-05-13T00:24:02+02:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "docs-gpt"
primary_region = "jnb"

[build]
  dockerfile = "Dockerfile"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 1
